### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gep13** [Ninglin/Cake.Jira#2]
Can you please confirm if this is the repository for this NuGet package:

https://www.nuget.org/packages/Cake.Jira/

The Project Site isn't listed in the nuspec, so I just wanted to make sure.  Thanks

**Comment by Ninglin** [comment]
hey @gep13. Sorry for the late response. I somehow missed the notification. Yes I can confirm that is true. I have got to update the nuspec with that.

**Comment by Ninglin** [comment]
After checking nuget.org the project site is listed. You must've seen an earlier version which was delisted.

**Comment by gep13** [comment]
@Ninglin thanks for getting back to me about this! Yes, that could well be the case. Looks like it is indeed all sorted now!
