### ISSUE TITLE
Recommended changes resulting from automated audit

### ISSUE THREAD

**Issue by Jericho** [Ninglin/Cake.Jira#3]
We performed an automated audit of your Cake addin and found that it does not follow all the best practices.

We encourage you to make the following modifications:

- [ ] You are currently referencing Cake.Core 0.23.0. Please upgrade to 0.28.0
- [ ] Your addin should target netstandard2.0. Please note that there is no need to multi-target, netstandard2.0 is sufficient.
- [ ] There should be a YAML file describing your addin on the cake web site. Specifically, you should add a `.yml` file in this [repo](https://github.com/cake-build/website/tree/develop/addins)

Apologies if this is already being worked on, or if there are existing open issues, this issue was created based on what is currently published for this package on NuGet.org and in the project on github.

**Comment by Ninglin** [comment]
Hey @Jericho. I'll try to catch up on this this week.

**Comment by Ninglin** [comment]
@Jericho I've gone thru the changes. Version 0.5 of the addin should conform to those standards. Can you rerun the audit and get back to me so we can close this?

**Comment by Jericho** [comment]
The automated audit tool runs automatically at noon and midnight GMT and generates a report which you can see here: https://github.com/cake-contrib/Home/blob/master/Audit.md

**Comment by Ninglin** [comment]
Closing this. Last report was ok and I've already opened [website#595](https://github.com/cake-build/website/pull/595)
![image](https://user-images.githubusercontent.com/1248732/48695223-844d7e80-ebd6-11e8-95ff-2fb2935a6ca9.png)
